### ISSUE TITLE
`getItemYear` does not handle locale properly

### ISSUE THREAD

**Issue by krnl0x0** [Chronoblog/gatsby-theme-chronoblog#44]
I've noticed an incosistency of handling "year locale":

https://github.com/Chronoblog/gatsby-theme-chronoblog/blob/d01f55746a5f62125c6daaffbea89c6c7b429e9e/packages/gatsby-theme-chronoblog/src/components/feed-items/feed-items.js#L103-L104

Above code passes `lang` parameter, but in the below code, `lang` is not given and thus remaining `undefined`:

https://github.com/Chronoblog/gatsby-theme-chronoblog/blob/d01f55746a5f62125c6daaffbea89c6c7b429e9e/packages/gatsby-theme-chronoblog/src/components/feed-items/feed-items.js#L297

This will lead to the comparison of two different locale years, one is `en-US`, the other is `undefined` (default locale). So in my case that uses `zh-CN` locale, latter will produce `"2020年"` instead of `"2020"`.

**Comment by Ganevru** [comment]
Hello! Thank you for giving an explanation of the problem.

I made a repository for testing the Chinese language (zh-CN) https://github.com/Chronoblog/gatsby-starter-chronoblog-chinese-language-test (web: https://gatsby-starter-chronoblog-chinese-language-test.now.sh ) to make it easier to track problems (yes, in this case it will not help much since there is a dependence on the development environment, but still).

As I understand it, all that needs to be done is to write the default value lang = 'en-US' on line 98:

`` ``
const getItemYear = (item, lang = 'en-US') => {
`` ``

but I need to test everything so that nothing is broken.

**Comment by Ganevru** [comment]
I posted a new version: 0.22.0, the problem seems to be fixed.

@krnl0x0 - check if everything works fine.

**Comment by krnl0x0** [comment]
@Ganevru The test seems totally fine, nice work😉
